plugins:
  cron_settings:
    description: "<p>Provide tool to control codebase state.</p>\r\n"
    actions: "<p>Install and configure some advanced cron module.</p>\r\n"
    impatcts: 'If system cron doesn’t work or/and Drupal cron was setted up incorrectly it can lead to a lot of problems: <br><ul><li>Drupal will not provide system-wide defaults to running jobs at particular times, storing (caching) web pages to improve efficiency, and performing other essential tasks.</li> <li>Drupal will not periodically clean up log files</li> <li>application will not have a possibility automatically update feeds</li> <li>update manager will not have a possibility to check automatically pending updates</li> <li>search indexes that also uses cron will not index new/updated content and many other points</li></ul>'
    fail: "<p>Its fail message49</p>\r\n"
    success: "<p>Success message!!</p>\r\n"
    help: 'Check cron settings.'
    impacts: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duo Reges: constructio interrete. Satis est ad hoc responsum. Quid vero? Primum quid tu dicis breve?</p>\r\n\r\n<p>&nbsp;</p>\r\n"
  configuration_manager_status:
    description: 'Check current status of config files via configuration manager and provide the status.'
    actions: 'Review and update configurations'
    impacts: 'There are should not be any changes in config files because next deployment may revert all that changes. All the configuration changes on the site should be immediately imported into the configuration files through the config manager and must be updated in the project code.'
    fail: 'There are differences between configurations stored in database and files.'
    success: 'All config files are actual.'
    help: 'Check non-security updates for modules.'
  drupal_core:
    description: "Check the Drupal core version and its actuality."
    actions: "Enable core aggregation or use @link (that includes all latest security updates)."
    impatcts: 'If you don’t monitor for new versions and ignore core updates, your application is in danger as hackers follow security-related incidents (which have to be published as soon as they''re discovered) and try to exploit the known vulnerabilities. Also each new version of the Drupal core contains bug fixes, which increases the stability of the entire platform.'
    fail: "Current Drupal core version is outdated - @version"
    success: "Current Drupal core version is up to date - @version"
    help: 'Check the Drupal core version and its actuality.'
  features_status_check:
    description: 'Features provides a centralized place to manage, configure and export components and write them to code. This convenience makes Features an excellent tool for managing changes (for Drupal7) between development environments and version control in conjunction with Git, SVN, or other version control systems.'
    actions: 'It is recommended to update features with the latest structure and settings done in the BO.'
    impacts: 'statuses overridden, needs review and rebuilding must be avoided because it means that configurations that are defined in the feature module''s code have been overridden in the Drupal backend by a user and during next execution of features revert execution (that is a part of any normal Continuous Deployment process) these changes will be lost.'
    fail: 'There are non-actual features on web-site.'
    success: ''
    help: 'Check if all Features are actual.'
